### ISSUE TITLE
objective function wrapper for optimizer. should be in PE or Tuner. also bug in GenSA

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#101]
GenSA creates this on fly. I think this needs to be generalized

**Comment by berndbischl** [comment]
actually the whole function seems wrong and does not call eval_batch?

**Comment by mllg** [comment]
> actually the whole function seems wrong and does not call eval_batch?

https://github.com/mlr-org/mlr3tuning/blob/master/R/TunerGenSA.R#L46

?

**Comment by berndbischl** [comment]
> https://github.com/mlr-org/mlr3tuning/blob/master/R/TunerGenSA.R#L46
> 
> ?

my comment was wrong / or is now refactored. important point is the generalization to PE and the rereading of the function
