### ISSUE TITLE
TerminatorRunTime: it seems mlr3 already stores the runtime of all bmr evals. maybe we should simply read it out?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#109]

**Comment by berndbischl** [comment]
also the proc.time call in the terminator is probably not correct. what about subprocesses?

**Comment by mllg** [comment]
What's wrong with `proc.time()`?

**Comment by berndbischl** [comment]
> What's wrong with `proc.time()`?

i thinks thats irrelvant now, if we as discussed take the time measured by mlr out of the BMR? then i dont have to measure here at all.
and we have the 2nd wallclock-time-terminator, and that simply compares clock times?

**Comment by mllg** [comment]
Ok, was just curious.

**Comment by berndbischl** [comment]
done and renamed to EvalTime
