### ISSUE TITLE
should numeric tuners also be able to tune int spaces?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#117]
example: currently GenSA specifies it can only handle numeric stuff

**Comment by berndbischl** [comment]
and with numeric we apparently mean double

**Comment by mllg** [comment]
Yes, they should.

**Comment by berndbischl** [comment]
would actually be easier if we cleanly say that eg GenSA can only do doubles, and force the user to build a trafo which rounds?

**Comment by berndbischl** [comment]
there is already a unit test with GenSA that demos that this works

**Comment by be-marc** [comment]
This is covered in a future gallery post https://github.com/mlr-org/mlr3gallery/pull/60.

**Comment by be-marc** [comment]
Closed by mlr-org/mlr3gallery#60
