### ISSUE TITLE
tuner$values does not return a vector from paramset

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#121]
but potentially also other values from the configured learner
that can be confusing i guess?
test with rpart, then the default "xval" is also in there..

**Comment by berndbischl** [comment]
for that reason in test_tuner i now add +1 here

  expect_list(r$values, len = n_dim + 1)

which feels wrong

**Comment by berndbischl** [comment]
maybeo have options here, for the bare vec and the complete one
and for tranfsormed

**Comment by berndbischl** [comment]
we need to carefully check what we set in AutoTuner

**Comment by berndbischl** [comment]
probably related to #51

**Comment by berndbischl** [comment]
the problem now is: Tuner:tune is a function that transforms an instance in a tuning result.
i like that.
but that basically means the result has ONE format. because after i have done the computation, i cannot set an option for the format anymore?

i mean i can  add an option to "tune()" but that seems bad. because i have to set that option before the computation and not afterwards when querying the result?

i guess the solution would be to disentangle the computatation from the querying of the result?

so tune() returns "void" and there would be "tune_result()" with some options?

@mllg

**Comment by mllg** [comment]
199e63852456bc5757d68f141d547b529f3c0fee splits the methods. Unsure what "formats" we really need.

**Comment by berndbischl** [comment]
> [199e638](https://github.com/mlr-org/mlr3tuning/commit/199e63852456bc5757d68f141d547b529f3c0fee) splits the methods

we are working on the same thing. i did this:

https://github.com/mlr-org/mlr3tuning/tree/tuner_select_best

isnt this better?

**Comment by mllg** [comment]
Similar: yes, better: IDK.

I don't like that the best RR is duplicated in a private slot. Why is this not simply an AB?

**Comment by berndbischl** [comment]
It's only a reference?

**Comment by berndbischl** [comment]
And the reason is the tuner needs to assign this at the end? That's the main point?

**Comment by berndbischl** [comment]
Please read the other related issue

**Comment by berndbischl** [comment]
we have in the instance now:
result_config, result_config_complete
