### ISSUE TITLE
check for duplicted exps in batch_eval

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#127]
if that happens wir directly return the y
we NEED to document what that means for Terminators...

**Comment by berndbischl** [comment]
hash = function(...) { digest::digest(list(...), algo = "xxhash64") } 
hash_resample_iteration = function(task, learner, resampling) { hash(task$hash, learner$hash, resampling$hash) }
hash = function(...) { digest::digest(list(...), algo = "xxhash64") }
hash_resample_iteration = function(task, learner, resampling) { hash(task$hash, learner$hash, resampling$hash) }
digest(list(task$hash, learner$hash, resampling$hash), algo = "xxhash64")

**Comment by mllg** [comment]
This seems to be outdated as the data storage is not based on a BMR anymore? Reopen if I've overlooked something.

**Comment by berndbischl** [comment]
i think you are overlooking something? if we reeval the same point, we still redo the experiment?

**Comment by be-marc** [comment]
Discussion moved to #203
