### ISSUE TITLE
Tuner:tune_result, how to select best RR

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#134]
See this issue https://github.com/mlr-org/mlr3/issues/320

we also need some form of tie handling

**Comment by berndbischl** [comment]
also the "best" function should probably live in the PE

**Comment by berndbischl** [comment]
PE already has a best() function now duplicated with mlr3, with the same problems as reported in my issue

**Comment by mllg** [comment]
Removed the `$best()` method in mlr3.

**Comment by berndbischl** [comment]
> Removed the `$best()` method in mlr3.

will implement it here now

**Comment by berndbischl** [comment]
i have implemented it now in PE, but the function needs some unit tests

**Comment by berndbischl** [comment]
@mb706 @mllg what config do you want to have the Tuner return in case of ties?
first, last or random?

**Comment by berndbischl** [comment]
the ties.method default need to be set in Tuner and PE

**Comment by berndbischl** [comment]
we have tie-handling now and at least some tests

**Comment by berndbischl** [comment]
now dupllicated with #144
