### ISSUE TITLE
GenSA and Tuners in general: dont we have to require the namespace?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#136]
because currently we do not?

is this valid code:
```
      GenSA::GenSA(fn = objective, lower = self$pe$param_set$lower, upper = self$pe$param_set$upper,
        control = self$settings, pe = self$pe)
```
for a suggested package?

**Comment by berndbischl** [comment]
@mllg

**Comment by berndbischl** [comment]
also a tuner should probably have slot "packages"?

**Comment by mllg** [comment]
The tuner should call `requireNamespace()` / `require_namespaces()` before calling a function of `GenSA`. This is currently more good practice than technically required. It should also have a slot packages, so that mlr3 can handle the package loading for the AutoTuner.

**Comment by berndbischl** [comment]
> The tuner should call `requireNamespace()` / `require_namespaces()` before calling a function of `GenSA`. This is currently more good practice than technically required. It should also have a slot packages, so that mlr3 can handle the package loading for the AutoTuner.

ok. thx, exactly as I thought - but not there currently
