### ISSUE TITLE
tuners should have some properties. 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#137]
eg. GenSA can only handle numerics
these should also be displayed in their dictionary

**Comment by mllg** [comment]
See `Learner$feature_types`. The `AutoTuner` should just set this field accordingly.

**Comment by berndbischl** [comment]
> See `Learner$feature_types`. The `AutoTuner` should just set this field accordingly.

? that has nothing to do with the AutoTuner? and nothing to do with feature types of a learner? 
its what hyperparams a tuner can optimize? 

its maybe a similar concept but absolutely not the same thing?

**Comment by mllg** [comment]
Oh right, was confused.

**Comment by berndbischl** [comment]
Tuner now has "param_classes" it supports
