### ISSUE TITLE
PerfEval using ParamSet with trafo

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3tuning#138]
[this](https://github.com/mlr-org/mlr3tuning/blob/370c9140a01223a44ef62b889c88d0b63696c59d/R/PerfEval.R#L128-L132) looks like a bug to me, because `Design$transpose()` already has argument `trafo` default set to `TRUE`. Also `param_set$trafo()` works with `list`s, not with `data.table`s if I remember correctly.

**Comment by berndbischl** [comment]
possible, the whole class is still marked for review

**Comment by berndbischl** [comment]
duplicated
