### ISSUE TITLE
Check error handling and fallbacks for tuner

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#14]
This needs to be done. Test setup could be:
- debug learner with parameter space including `error_train` and `error_predict`
- featureless learner as fallback learner

Add a section to the tuner vignette on how to see what really happens during the tuning.

**Comment by schalkdaniel** [comment]
connected to #7

**Comment by mllg** [comment]
Added tests + example in e1ab00cacc33d73562fa0ca7d9a95d4c9151e06c. Will open a new issue in mlr3book.
