### ISSUE TITLE
PerfEval rename?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#142]
@mb706 likes TuningScenario or TuningState better

**Comment by berndbischl** [comment]
BB maybe like TuningScenario

**Comment by berndbischl** [comment]
TuningInstance

**Comment by berndbischl** [comment]
@mllg vote please?

**Comment by mllg** [comment]
TuningInstance and TuningState sound good to me. However, it would help to see which methods are now in there.

**Comment by berndbischl** [comment]
The PerfEval class is somewhat finished now, you can inspect it

**Comment by berndbischl** [comment]
I rather like TuningScenario, 2nd choice would be TuningInstance
