### ISSUE TITLE
eval_batch: maybe add an extra arg that allows the tuner to save information in the archive

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#145]

**Comment by berndbischl** [comment]
you are already working on this @mllg

**Comment by mllg** [comment]
Tuners already have access to the instance (and hence the BMR). Without a specific use case, the API is completely unclear and this won't get anywhere.

**Comment by berndbischl** [comment]
Its already solved I guess by what you did. All seems fine. I created the issue before our recent discussion of rrdata in bmr
