### ISSUE TITLE
TuningInstance currently only stores the trafoed values.

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#155]
i dont wnat to overcomplicate things, but if we dont store the other stuff we can never go back

**Comment by berndbischl** [comment]
and eg couldnt plot on the orginal scala

**Comment by berndbischl** [comment]
maybe simply add a list col so we store the untrafoed configs in the archive?

**Comment by berndbischl** [comment]
@mb706 @mllg i would like to hear your comments here. this might be a problem as we can never go back from trafoed to untransformed

**Comment by mllg** [comment]
Well, store the untransformed values?

**Comment by berndbischl** [comment]
the problem is, you store the the values, in the learner. and i rely on that. i can now add the redundant info.

a) do we want that?
b) where? in the rr_data?

**Comment by mllg** [comment]
If you cannot transform back, it is not redundant. `rr_data` would be the best place, yes. OTOH, if we don't need this now, maybe focus on more important stuff.

**Comment by berndbischl** [comment]
just asking for later, but i guess the stored data should be somewhat complete and perfect

**Comment by berndbischl** [comment]
they are stored now in rr_data and accessible via "archive"
we need to document this a bit better, and maybe check the names in the archive.
also unnest probably needs to be changed to "none", "trafo", "untrafo"

**Comment by berndbischl** [comment]
i fixed the docs and cleaned up names, see #195 
also changed unnest to the options above
