### ISSUE TITLE
TerminatorNone: not needed?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3tuning#158]
Wouldn't it be more intuitive to just not provide a terminator instead of having to specify a "TerminatorNone"?

**Comment by berndbischl** [comment]
if we allow NULL interally, we dont have a safe type in the terminator slot. that seems bad.

I have nothing against a smart default from the outside, but internally the TNone should stay i think.
and this is simply sugar? 

i am for closing this

**Comment by berndbischl** [comment]
sorry to be picky but your commit seems pretty bad? 
if you set this to none as a default in the instance, doesnt that open up multiple scenarios for infinite loops?

**Comment by berndbischl** [comment]
can we pls not do this now, i rather have the user set this up manually and write that extra line than this

**Comment by mllg** [comment]
If you do not want it, revert.
