### ISSUE TITLE
Nested resampling outer resampling

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#16]
We have to replace the resampling object of the fitness function with an `ResamplingCustom` object to correctly evaluate the performance. This is not possible at the moment. See https://github.com/mlr-org/mlr3/issues/108

At the moment we just use a holdout to see that it works in general:
```
# We want this:
resampling_temp = ResamplingCustom$new()
resampling_temp$instantiate(self$ff$task, train_sets = list(train_set_temp))

# But doint that:
resampling_temp = ResamplingHoldout$new()
self$ff$resampling = resampling_temp

# To use the fitness function functionality:
self$ff$eval(tuner_temp$tune_result()$param_vals)
```

I also think that we should keep this structure and use `eval` of the fitness function since this handles the registration in the benchmark result etc. automatically.

**Comment by berndbischl** [comment]
> We have to replace the resampling object of the fitness function with an `ResamplingCustom` object to correctly evaluate the performance

can you please explain what this means? it sounds worrysome and i dont get it

**Comment by schalkdaniel** [comment]
The problem is that in nested resampling for the outer resampling we have a different parameter in each fold and therefore we cannot use resampling objects out of the box. 

To do nested resampling we filter the task of the inner tuner regarding the indexes of the current fold and then use the best parameter setting to conduct an outer resampling step. And that's the reason why we overwrite the resampling object of the fitness function. 

Another reason for this is that we can then use `eval` of the tuner which automatically builds the benchmark result and does all the other stuff.

**Comment by schalkdaniel** [comment]
We have talked about this, so I think we can close this, right?
