### ISSUE TITLE
should eval_batch return a bit more?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#161]
maybe the currently evaled BMR? too? that would be nice?

**Comment by berndbischl** [comment]
we agreed:
- eval_batch returns nothing only computes
- we create an AB for the last evalued BMR-block
- we create and AB for the last aggreagted performance data table on the last block

**Comment by berndbischl** [comment]
actually these 2 ABs could even have an argument for the block to return, an integer. do we have an "iteration" nr we save in the path?

**Comment by mllg** [comment]
> * we create an AB for the last evalued BMR-block
> 
> * we create and AB for the last aggreagted performance data table on the last block

Do we really need this? `eval_batch()` currently returns the batch number + new hashes. Do we need this in other places?

**Comment by berndbischl** [comment]
I think Neary every tuner who acts on his results need this

**Comment by berndbischl** [comment]
as you are already returning a list i added this as 3rd field

```
#'   * `"batch_nr"`: Number of the new batch.
#'     This number is calculated in an auto-increment fashion and stored also stored inside the [BenchmarkResult] as column `batch_nr`
#'   * `"hashes"`: hashes of the added [ResampleResult]s.
#'   * `"perf"`: A data.table of evaluated performances for `dt`. Has the same nr of rows as `dt`, and the same nr of columns as `measures`. Columns are named with measure-IDs.
#'     A cell entry is the (aggregated) performance of that configuration for that measure.
```

this does what we want now what we return is absolutely enough
