### ISSUE TITLE
bmr: dob naming issue

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#166]
can we please maybe use a more appropriate name here?
is this name also used in mlr3? yes i think?

it should be something else IMHO

**Comment by berndbischl** [comment]
ah no its only used in mlr3tuning. ok.

**Comment by berndbischl** [comment]
batch_nr? 
batch_iter?

**Comment by berndbischl** [comment]
eval_nr?
eval_stage?

**Comment by berndbischl** [comment]
--> batch_nr seems best?

**Comment by berndbischl** [comment]
or batch_counter

**Comment by berndbischl** [comment]
also if this is introduced it needs to be doced

**Comment by mllg** [comment]
Done in cb3f7b0e18195bf26eef8b04c893a2d7778ec9f0.
