### ISSUE TITLE
doc / comment issue

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#173]
@mllg 
if you this 

TuningInstance
```
      best = if (measure$minimize) which_min else which_max
      tab$resample_result[[best(y, na_rm = TRUE)]]
```

please add an inline code comment why NA removal is necessary (and not only: "for good measure / defensive / to make sure")

and also please point to the mlr3 docs which explain why an NA can be returned by BMR$aggregate

**Comment by berndbischl** [comment]
i just read the BMR docs. aggregate does not mention NAs at all
the same holds true for Learner$predict, which is probably the reason why an NA might be produced by a measure. Which is probably the 3rd class which is related here, API/ doc-wise

**Comment by berndbischl** [comment]
will keep this open until we decide what happens with metric and NAs

**Comment by be-marc** [comment]
We do not allow NAs in the `Archive` anymore. The issue that `bmr$aggregate` in `ObjectiveTuning` can possibly return an `NA` might be solved by the `Measure`s directly.
