### ISSUE TITLE
the TuningInstance$best function must be generalized

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#174]
we want each tuner to freely decide the resampling experiment itself. but the function has become rather complex including errorhandling. 

i think it should have something like a subset of hashes that it selects the best from

**Comment by berndbischl** [comment]
review  this before 0.2, maybe close

**Comment by be-marc** [comment]
This is outdated. `bbotk::Archive$best()` is a simple method without tuning specific error handling.
