### ISSUE TITLE
noisy / aggregation problem: how do we handle the fact that some tuners might evalutae some configs multiple times?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#175]
this relates to the archive function but also the selection of the final best

**Comment by berndbischl** [comment]
the problem is that the tuner might run a different resampling on the some config multiple times. now MAYBE we want to aggregate over this? to producde noise-reduction via averaging?
but which "grouping"  column helps us to do this?

**Comment by berndbischl** [comment]
@mllg we should still discuss this

**Comment by be-marc** [comment]
irace shows how to run the same configuration on different resamplings. The tuner adds a grouping variable to the archive and implements it's own `.assign_result` function.
