### ISSUE TITLE
Tuner can crash now if identical experiments are being run

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#183]
this can happen. thats not very robust behavior...

test_TunerRandomSearch.R:5: error: TunerRandomSearch
BenchmarkResult$combine(): Identical hashes detected. Duplicated Resam
pleResults can not be combined into a single BenchmarkResult.

**Comment by berndbischl** [comment]
this risk is unfortunately increased when dependent params are involved. 
see here:
```
      param_set = ParamSet$new(
          params = list(
            ParamFct$new("p1", levels = c("a", "b"), default = "a"),
            ParamDbl$new("p2", lower = 0, upper = 1)
          )
      )
```
we often run p1=a

see related issue #127

**Comment by berndbischl** [comment]
for that reason i disabled all test_tuner_dependencies tests
these MUST be reenabled

**Comment by mllg** [comment]
See https://github.com/mlr-org/mlr3/pull/348.

**Comment by berndbischl** [comment]
i reenabled all tests and added a 2nd test
