### ISSUE TITLE
result_config: better as function? 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#187]
currently we have 2 ABs
we also probably need an option to trafo the results

**Comment by berndbischl** [comment]
also we probably want to separate out the assign-part as the user never needs this? and we can join this in one assign function?

**Comment by mllg** [comment]
My suggestion:

```r
instance$result(method = ...) -> list(method = character(1), config = list(), performance = numeric())
```

**Comment by berndbischl** [comment]
its a function now, and the internal state is a list. i also always return untrafoed and trafoed configs. 
but wether to mix in learner params is an option
