### ISSUE TITLE
Tuner$tune() should not return self

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3tuning#192]
We briefly talked about this. `Tuner$tune()` returning `self` would suggest that it mutates the `Tuner` object, but that does not appear to happen. Other options
1. Return some kind of result. Drawback is that the result could be complex and would fit better in the TuningInstance object.
2. Return the `TuningInstance` object instead.

I would favour 2., together with `clone()`-ing the input `TuningInstance` object. This mostly for consistency with other R things, but I know people may disagree.

**Comment by berndbischl** [comment]
how about then returning simply invisible(NULL)? i think that seems most clean as the caller has the instance reference always "in hand"?

**Comment by berndbischl** [comment]
and it is clear then that no interesting result is returned and no programming mistkae can happen?

**Comment by berndbischl** [comment]
i have opted to return NULL, only reopen if you heavily disagree pls
