### ISSUE TITLE
Autotuner using fixed resampling instance internally

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3tuning#197]
If this is already possible I haven't seen it; Is it possible to do nexted resampling with the autotuner, using a fixed resampling instance for inner resampling?

**Comment by berndbischl** [comment]
no, we have never supported this yet, in mlr2 or mlr3. 
you would have to clearly define how this should work in general. 
eg assume this: on the outer level you have training sets T1 and T2. further assume they are not even the same size.
now on the inner level we want to do 10CV
a) it is very easy to specify the 10CV splitting as a function/strategy. this can be applied then to T1 and T2. mlr does exactly that, we use an uninstantiated resampling object for this.

b) it seems hard to write down fixed inner splits now?

i know for train valid test thats possible (in theory, not in mlr). but for looped splitting like above?

**Comment by mb706** [comment]
One could at least supply something like a CV seed so the CV gets initialized the same way. That ensures that if the outer CV is fixed and I am calling the autotuner multiple times (e.g. with different learners, or wirh different tuning algorithms) I get the same inner resampling split per outer resampling fold. But maybe it does not make much difference in the end? I guess if the UI complexity outweigh the benefit we can close.

**Comment by ercbk** [comment]
Just came across this problem myself. I'm going through different nested cv implementations and am working on the mlr3 one right now. I don't see how you can have a rigorous algorithm comparison without consistent folds/bootstraps. I like the CV seed idea. Also, the rsample package has a nested cv [function](https://tidymodels.github.io/rsample/reference/nested_cv.html) and [here's](https://github.com/rasbt/stat479-machine-learning-fs19/blob/master/11_eval4-algo/code/11-eval4-algo__nested-cv_verbose1.ipynb) a Python version. Maybe there's some inspiration in one of those. Apologize if you guys have already seen them. Hope you get this figured out. It's been fun messing around with this R6 version of mlr and I'd like to try it out.

**Comment by be-marc** [comment]
The AutoTuner accepts instantiated resamplings now. In case of nested resampling, it checks if all required row ids are available.
