### ISSUE TITLE
PerfEval bug: could not find function "expand_grid"

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3tuning#202]
Running the example in the documentation for `?PerfEval` on the latest version of mlr3tuning on CRAN (v.0.1.0). I get the error

```
Error in expand_grid(tasks = list(self$task), learners = learners, resamplings = list(self$resampling)) : 
  could not find function "expand_grid"
```

For reference the example:
```R
library(mlr3)
library(paradox)
library(data.table)
# Object required to define the performance evaluator:
task = mlr_tasks$get("iris")
learner = mlr_learners$get("classif.rpart")
resampling = mlr_resamplings$get("holdout")
measures = mlr_measures$mget("classif.ce")
param_set = ParamSet$new(params = list(
  ParamDbl$new("cp", lower = 0.001, upper = 0.1),
  ParamInt$new("minsplit", lower = 1, upper = 10)))

terminator = TerminatorEvals$new(5)
pe = PerfEval$new(
  task = task,
  learner = learner,
  resampling = resampling,
  measures = measures,
  param_set = param_set,
  terminator = terminator
)
pe$eval_batch(data.table(cp = c(0.05, 0.01), minsplit = c(5, 3)))
```

**Comment by RaphaelS1** [comment]
Same bug also occurs when using `tune` from any tuner

**Comment by berndbischl** [comment]
uh what? the class "PerfEval" should not exist since longer time. it vanished in refactoring. same for "expand_grid", which was refactored to "benchmark_grid" - but in mlr3. 

i also searched the repo, the strings "PerfEval" and "expand_grid" in the repo they dont seem to exist. where are you taking this from?

**Comment by berndbischl** [comment]
@mllg

**Comment by berndbischl** [comment]
i just installed from cran.

> library(mlr3tuning)
> ?PerfEval
No documentation for 'PerfEval' in specified packages and libraries:

**Comment by RaphaelS1** [comment]
That is very strange... When I installed and ran 2 days ago I got the above but I agree `PerfEval` is now gone...

Although I am now getting a different error when running the following example from the documentation

```R
library(mlr3)
library(paradox)
param_set = ParamSet$new(list(
  ParamDbl$new("cp", lower = 0.001, upper = 0.1)
))
terminator = term("evals", n_evals = 3)
instance = TuningInstance$new(
  task = tsk("iris"),
  learner = lrn("classif.rpart"),
  resampling = rsmp("holdout"),
  measures = msr("classif.ce"),
  param_set = param_set,
  terminator = terminator
)
tt = tnr("random_search") # swap this line to use a different Tuner
tt$tune(instance) # modifies the instance by reference
instance$result # returns best configuration and best performance
instance$archive() # allows access of data.table / benchmark result of full path of all evaluations
```

Again the error is of the same form but in reference to a different function:

```
Error in ids(self$measures) : could not find function "ids"
```

**Comment by RaphaelS1** [comment]
I have no idea what happened before but I'll put it down to something buggy, this time I've restarted my R session, re-installed everything from CRAN and only run the above example

**Comment by mllg** [comment]
Are you sure you updated everything? Can you provide a `sessionInfo()`?

My guess: You need to update `mlr3misc`.

**Comment by RaphaelS1** [comment]
Yes you're right working now! In which case would it be possible to add the required package version numbers to the description file?

**Comment by berndbischl** [comment]
> In which case would it be possible to add the required package version numbers to the description file?

thats the only bug on our side. i will do this now:

but on your side: 
please really print out the sessionInfo, before you post, then update all packs from cran.
check if this resolves the issue. if it does, you may / should still create an issue, so we can update the DESC. 
but in all issues of this type pls always include your sessionInfo in the post

**Comment by berndbischl** [comment]
did it now, closing
@mllg maybe check this before uploading a bit more, we are changing too much "down below" and dont want more issues of this type
