### ISSUE TITLE
do we want to allow to run-continue on an instance that already has evals?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#204]
see #203 for an example (a weird one)
for RS  this might make sense.
think about this also for other tuners

also we might need a "reset" function to "clean" the instance?

**Comment by jakob-r** [comment]
We already allow that. We just don't test it so well.
The following works well:

```r
ps = ParamSet$new(params = list(
      ParamDbl$new("cp", lower = 0.1, upper = 0.3)
    ))
term = term("evals", n_evals = 2)
inst = TuningInstance$new(tsk("iris"), lrn("classif.rpart"), rsmp("holdout"), msr("classif.ce"), ps, term)
tuner = tnr("random_search")
tuner$tune(inst)
inst$terminator = term("evals", n_evals = 10)
tuner$tune(inst)
```


> also we might need a "reset" function to "clean" the instance?

Just reconstruct it then?

**Comment by berndbischl** [comment]
Well. Yes agreed we want to allow it. But my gut feeling is we haven't thought it through. Not having tests is evidence for this

**Comment by berndbischl** [comment]
also we clearly need to define how tuning algos handle the data already in the instance. BO would certainly use it for a warm start, most other and currently implemented algos would ignore it

**Comment by pfistfl** [comment]
Absolutely wants this. This makes warm-starting etc. possible. 

Additionally, we can now "tune for a few minutes", and then decide if we want to tune further
This was afaik missing in mlrMBO.

**Comment by jakob-r** [comment]
OT:
> This was afaik missing in mlrMBO.
It's possible but not (well) documented in mlrMBO. I should probably write a Vignette for this topic.

**Comment by be-marc** [comment]
`TuningInstance*` can be restarted like this:

```r
  learner = lrn("classif.rpart", xval = 0)
  learner$param_set$values$cp = to_tune(0.1, 0.3)

  instance = TuningInstanceSingleCrit$new(task = tsk("iris"), learner = learner,
    resampling = rsmp("holdout"), measure = msr("classif.ce"),
    terminator = trm("evals", n_evals = 4))

  tuner = tnr("random_search", batch_size = 2)
  tuner$optimize(instance)
  expect_data_table(instance$archive$data, nrows = 4)

  instance$terminator = trm("evals", n_evals = 8)
  instance$is_terminated = FALSE

  tuner$optimize(instance)
  expect_data_table(instance$archive$data, nrows = 8)
```

> also we might need a "reset" function to "clean" the instance?

Implemented as `OptimInstance$clear()` in bbotk.

Reopen if more needs to be done.
