### ISSUE TITLE
AutoTuner spits out strange error

### ISSUE THREAD

**Issue by sguidi11** [mlr-org/mlr3tuning#205]
Hi, 
I am migrating some code from mlr to mlr3.  When I run the following code, during the train part the "AutoTuner" function kicks out a strange error: Any ideas ? 

> library(mlr3)
> library(paradox)
> library(mlr3tuning)
> 
> task = tsk("iris")
> learner = lrn("classif.rpart")
> resampling = rsmp("holdout")
> measures = msr("classif.ce")
> param_set = ParamSet$new(  params = list(ParamDbl$new("cp", lower = 0.001, upper = 0.1)))
> terminator = term("evals", n_evals = 5)
> tuner = tnr("grid_search")
> at = AutoTuner$new(learner, resampling, measures, param_set, terminator, tuner)
> at$store_tuning_instance = TRUE
> at$train(task)
INFO  [08:56:35.076] Starting to tune 1 parameters with '<TunerGridSearch>' and '<TerminatorEvals>' 
INFO  [08:56:35.086] Terminator settings: n_evals=5 
INFO  [08:56:35.098] Evaluating 1 configurations 
INFO  [08:56:35.108]     cp 
INFO  [08:56:35.108]  0.012 
INFO  [08:56:35.134] Benchmark with 1 resampling iterations 
INFO  [08:56:35.142] Applying learner 'classif.rpart' on task 'iris' (iter 1/1) 
INFO  [08:56:35.169] Finished benchmark 

**### **Error in if (lg$threshold >= 400) { : 
  missing value where TRUE/FALSE needed****

> traceback()
16: instance$eval_batch(g$data[inds])
15: private$tune_internal(instance)
14: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch({
        private$tune_internal(instance)
    }, terminated_error = function(cond) {
    })
10: self$tuner$tune(instance)
9: learner$train_internal(task = task)
8: .f(learner = <environment>, task = <environment>)
7: eval(expr, p)
6: eval(expr, p)
5: eval.parent(expr, n = 1L)
4: invoke(.f, .args = .args, .opts = .opts, .seed = .seed)
3: encapsulate(learner$encapsulate["train"], .f = train_wrapper, 
       .args = list(learner = learner, task = task), .pkgs = learner$packages, 
       .seed = NA_integer_)
2: learner_train(self, task, row_ids)
1: at$train(task)

> packageVersion("mlr3tuning")
[1] ‘0.1.0’
> packageVersion("paradox")
[1] ‘0.1.0.9000’
> packageVersion("mlr3") [1] ‘0.1.4.9000’
--
 
  |

**Comment by berndbischl** [comment]
It seems like the global state of the logger is not properly initialized? @mllg

**Comment by berndbischl** [comment]
Your example code is super vanilla this should not happen

**Comment by sguidi11** [comment]
Problem solved. I was using for whatever reason an old version of the "lgr" package
> packageVersion("lgr")
[1] ‘0.2.1’

**remotes::install_github("s-fleck/lgr")**

> packageVersion("lgr")
[1] ‘0.3.3.9000’

Thanks for helping out.

Samir

**Comment by berndbischl** [comment]
@mllg apparently already inceased the required version in the DESC file of mlr3 to

    lgr (>= 0.3.0),


so i think we are done here

https://github.com/mlr-org/mlr3/blob/master/DESCRIPTION
