### ISSUE TITLE
AutoTuner vignette

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#21]
We need this. Do also describe how nested resampling can be done with the AutoTuner.

**Comment by schalkdaniel** [comment]
Take also a look at the already existing mlr vignettes.

**Comment by pat-s** [comment]
I'll do this in _mlr3book_.

**Comment by pat-s** [comment]
Done in https://github.com/mlr-org/mlr3book/commit/2a8f28cc476213f00775125d496668d7691d9dac.

**Comment by pat-s** [comment]
> Show how to make simple graphics to illustrate results.

For this we need some code first, probably in _mlr3viz_. 
Let's see later into which part the eval plots fit best.
