### ISSUE TITLE
run unit test for tuning with deps in defaults

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#215]
i think the issue reported here is important enough to warrant a unit test with the usecase for tuning

https://github.com/mlr-org/paradox/issues/259

**Comment by jakob-r** [comment]
For completeness I will repeat what I said [here](https://github.com/mlr-org/paradox/pull/260)

The defaults are just a documentation (this was kind of our understanding IMHO):
- We cannot ensure that they are correct
- We never pass them explicitly to the learner
- ==> They are not reliable and should not be coded against.

If you want to tune a param that depends on the default just follow the very helpful error message and set the parameter manually in `lrn$param_set$values`.

**Comment by pat-s** [comment]
> If you want to tune a param that depends on the default just follow the very helpful error message and set the parameter manually in lrn$param_set$values.

Haven't read all of your discussion in #259 but is that the final statement you agreed on? If so, I would pass this as a solution to the initial question. Or is this still in discussion?

**Comment by be-marc** [comment]
We do not check this anymore by default. This can be activated with `check_values = TRUE`. In this case the dependency must be set. Unit tests in #440.
