### ISSUE TITLE
AT: the whole private$.param_set and cloning code is basically not understandable

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#221]
@mb706 wrote it
it really needs either to be changed or properly commented, this is central infrastructure

**Comment by berndbischl** [comment]
also, as it is not documented whats happens aand what is allowed it is unclear whether values-assignments like this work

```
  ps = TEST_MAKE_PS1()
  learner = lrn("classif.rpart")
  at = AutoTuner$new(learner, rsmp("holdout"), msr("classif.ce"), ps, term("evals", n_evals = 1), TunerRandomSearch$new())
  at$param_set$values$maxdepth = 1
print(at$param_set)
print(at$learner)
  expect_equal(at$param_set$values$maxdepth, 1)
  expect_equal(at$learner$param_set$values$maxdepth, 1)
```

currently they don't, as i figured out during trying to write a test, they might have worked before.
i am not sure if they should at at

can we maybe remove the paramset AB completely from the AT if this is so complex?

**Comment by mb706** [comment]
I am afraid this is some non-incidental complexity. If we want to have a param-set that both configures the tuner and the learner (and I think we do), and if R6 is not going to improve (which it probably won't too soon...) this is somethign that has to happen somewhere. I suggest that I
1. try to document stuff better or
2. try to move all the complexity somewhere else, e.g. a base-class from which autotuner (and PipeOpLearner, PipeOpLearnerCV, ...) could inherit.

Which would you prefer?

**Comment by be-marc** [comment]
We removed the paramset from the AT.
