### ISSUE TITLE
TuningInstance:eval_batch needs to properly assert that all rows in passed dt are feasible

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#228]
we had a bad bug in mlrhyperband

connected issues:
https://github.com/mlr-org/paradox/issues/268
https://github.com/mlr-org/mlr3hyperband/issues/41

**Comment by mb706** [comment]
Should happen in `Design$new()` when https://github.com/mlr-org/paradox/issues/268 is fixed
