### ISSUE TITLE
OOB inner resampling

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3tuning#236]
It's great that mlr3 Features the OOB of i.e. Random Forest as a Performance measures. It would be great If this could also be used to replace the inner Loop of nested resampling for Tuning. 

A hack like setting the holdout Ratio to 99 percent for holdout resampling and using the OOB as a measures should Work.

But is it possible to choose a different measure for inner and outer Evaluation ?

**Comment by jakob-r** [comment]
You can even use a holdout with 100% ratio for resampling in the AutoTuner in combination with an oob measure. Also you define different measures for the AutoTuner and the outer resampling (through the score function of the ResampleResult object). So it is already possible. Unless there is something not working I will close this Issue.
