### ISSUE TITLE
TuningInstance Docs

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3tuning#243]
TuningInstance should mention that it inherits additional fields and methods from `OptimInstance`.

**Comment by be-marc** [comment]
We have a similar issue in mlr3learners https://github.com/mlr-org/mlr3learners/issues/73. Methods from super classes are automatically listed by roxygen2 but fields are not. Maybe we just wait until roxygen2 adds support for fields https://github.com/r-lib/roxygen2/issues/1025. Close?

**Comment by be-marc** [comment]
We decided to wait for roxygen2.
