### ISSUE TITLE
access option store_models and store_resample results should be better doced

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#264]
from the current docs it is not understandable how this works
where do i set this? NB: the user does not create the ObjectiveFunction?

how do I access the results?

**Comment by berndbischl** [comment]
also try to make this visible in the cheatsheet

**Comment by berndbischl** [comment]
maybe we want to assert that this is not possible

instance:
  store_resample_results = FALSE,
  store_models = TRUE

**Comment by be-marc** [comment]
Docs and cheatsheet are updated and assertion is included
