### ISSUE TITLE
AutoTuner, how to pass the tuning method

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#28]
At the moment the tuning method is passed as factory:
```
at = AutoTuner$new(learner, resampling, param_set, terminator, tuner = TunerGridSearch,
  tuner_settings = list(resolution = 10L))
```

This is not very nice. We should pass an instantiated tuner object. The problem here is, that the tuner then already contains the task and it cannot be set by the autotuner which is required for nested resampling. Suggestion: The `tune()` member function of tuner gets a task for the tuning. This would be more consistent with `train(task)` and therefore much easier to use within the auto tuner.

What do you think about that?

**Comment by berndbischl** [comment]
I also don't hate your api above. But try your suggested change

**Comment by jakob-r** [comment]
+1 for passing the task in `TunerGridSearch$tune()` but would this break other stuff? I am bit out of the loop.

**Comment by schalkdaniel** [comment]
We want to pass a fitness function to tune or set it as active binding.
