### ISSUE TITLE
Tuner$param_classes should be an AB that points to Optimizer$param_classes

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3tuning#289]
When trying to e.g. change the `param_classes` of a Tuner, I currently have to do the following: 

```r
  tuner$param_classes = c(tuner$param_classes, "ParamUty")
  tuner$`.__enclos_env__`$private$.optimizer$param_classes = tuner$param_classes
```

`param_classes` should either be immutable OR changes to `param_classes` should also affect the underlying Optimizer's param_classes.

**Comment by be-marc** [comment]
`param_set`, `param_classes`, `properties` and `packages`  are immutable now. 

@pfistfl Do you really need to change these after creating the tuner? Or could you just create a new tuner with different properties?

**Comment by pfistfl** [comment]
was mostly due to https://github.com/mlr-org/bbotk/issues/123, so should be fine
