### ISSUE TITLE
Could we use a default measure for all tuning functions?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3tuning#294]
Resampling in mlr3 does not need a specific measure because we can calculate all measures afterwards.

For tuning the measure can influence the location of the optimum but for most measures it will be the same (i.e. accuracy/mce). So it could make sense to have automatic defaults?

The function `mlr3::as_measures(NULL, task_type)` returns a default measure.

**Comment by berndbischl** [comment]
the optimum location is really no argument. it will certainly be different for different measures.

of course we can use the default measure of the task type, but i really don't see too much value in here?
why not have it explicit?

**Comment by berndbischl** [comment]
we can use mlr3::default_measures(task_type)

**Comment by mllg** [comment]
`as_measure(NULL, task_type)` should also work
