### ISSUE TITLE
All of the mlr3book links on the readme are broken

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3tuning#308]
mlr3book chapters on [tuning search
    spaces](https://mlr3book.mlr-org.com/searchspace.html),
    [hyperparameter tuning](https://mlr3book.mlr-org.com/tuning.html)
    and [nested
    resampling](https://mlr3book.mlr-org.com/nested-resampling.html).

**Comment by be-marc** [comment]
Thanks. Done.
