### ISSUE TITLE
New performance stagnation terminator

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#34]
This terminator should measure the improvement and stops after, let's say, 5 iterations if no increase in performance is measured.

**Comment by epetrovski** [comment]
Having this feature would greatly improve the usefulness of `TunerRandomSearch`. Any way this could be assigned a higher priority?

**Comment by berndbischl** [comment]
i can try to squeeze in in more quickly, this should not be hard

**Comment by mllg** [comment]
A rough first prototype is in the stagnation branch, we need to clean up and discuss some other stuff first though.

**Comment by berndbischl** [comment]
> A rough first prototype is in the stagnation branch, we need to clean up and discuss some other stuff first though.

what is blocking?

**Comment by berndbischl** [comment]
1. mini issue: a better cleaner default seems to be threshold  = 0?
you need to exceed that so you dont need machine eps here?

2. more important: 
arent these formulas wrong?

```
      if (m$minimize) {
        min(perf_window) > min(perf_before) - pv$threshold
      } else {
        max(perf_window) < max(perf_before) + pv$threshold
      }
```

**Comment by berndbischl** [comment]
for minimize = TRUE it should be

min(perf_window) < min_perf_before - th?

**Comment by berndbischl** [comment]
also: do we have a unit test for correctness?

**Comment by mllg** [comment]
> for minimize = TRUE it should be
> 
> min(perf_window) < min_perf_before - th?

I'm confused now. 

This is `TRUE` if the performance in the last [iter] points (LHS) is better than the performance before (RHS), or in other words: we are still improving. So the answer to the question "should we terminate now" should be `FALSE`, right?

**Comment by mllg** [comment]
Changed the default of "threshold" in bb01bed27080fe021bc9df6dc6127738df40739f.

**Comment by berndbischl** [comment]
I think I was simply confused and tired. See now that it's good.

If we have 1 or 2 simple tests for correct behavior we can close
