### ISSUE TITLE
FitnessFunction sets ids of learners

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#35]
learners = mlr3misc::imap(design$transpose(), function(xt, i) {
        learner = self$learner$clone()
        learner$param_set$values = insert_named(learner$param_set$values, xt)
        learner$id = paste0(learner$id, n_evals + i)
        return(learner)
      })

please do NOT change stuff like this internally
the ID should stay as it is
and please unit tests that this does not happen

**Comment by mllg** [comment]
Fixed via 138da9c.
