### ISSUE TITLE
Early stopping with XGBoost graph learner [feature request]

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3tuning#376]
Hi @be-marc,

It will be really cool if we could have the early stopping [callback](https://mlr3tuning.mlr-org.com/reference/mlr3tuning.early_stopping.html) for XGBoost work on a graph learner. I recently adapted the [survival XGBoost](https://mlr3extralearners.mlr-org.com/reference/mlr_learners_surv.xgboost.html) learner to work with early stopping but when I tried to use it as a part of a graph learner as in below it wouldn't work:
``` r
library(mlr3proba)
#> Loading required package: mlr3
library(mlr3extralearners)
library(mlr3tuning)
#> Loading required package: paradox
library(survmob)

s = SurvLPS$new(ids = 'xgboost_cox_early')
dt = s$lrn_tbl()
grlrn = dt$learner[[1L]] # XGBoost Cox with distr prediction graph learner
grlrn
#> <GraphLearner:XGBoostCox>: Extreme Gradient Boosting (Cox)
#> * Model: -
#> * Parameters: XGBoostCox.booster=gbtree,
#>   XGBoostCox.early_stopping_set=test, XGBoostCox.nrounds=1,
#>   XGBoostCox.nthread=16, XGBoostCox.objective=survival:cox,
#>   XGBoostCox.verbose=0, compose_distr.form=ph,
#>   compose_distr.overwrite=TRUE
#> * Packages: mlr3, mlr3pipelines, mlr3proba, survival, distr6,
#>   mlr3extralearners, xgboost
#> * Predict Types:  [crank], distr, lp, response
#> * Feature Types: logical, integer, numeric, character, factor, ordered,
#>   POSIXct
#> * Properties: featureless, hotstart_backward, hotstart_forward,
#>   importance, loglik, missings, oob_error, selected_features, weights
param_set = dt$param_set[[1L]]
param_set
#> <ParamSet>
#>                             id    class     lower       upper nlevels
#> 1:          XGBoostCox.nrounds ParamInt 100.00000 1500.000000    1401
#> 2:              XGBoostCox.eta ParamDbl  -9.21034   -1.203973     Inf
#> 3:        XGBoostCox.max_depth ParamInt   2.00000    8.000000       7
#> 4: XGBoostCox.min_child_weight ParamDbl   0.00000    4.852030     Inf
#>           default value
#> 1: <NoDefault[3]>      
#> 2: <NoDefault[3]>      
#> 3: <NoDefault[3]>      
#> 4: <NoDefault[3]>      
#> Trafo is set.

task = tsk('lung')

xgb_at = AutoTuner$new(
  learner = grlrn,
  resampling = rsmp('holdout'),
  measure = msr('surv.brier'),
  search_space = param_set,
  terminator = trm('evals', n_evals = 5),
  tuner = tnr('random_search'),
  callbacks = clbk("mlr3tuning.early_stopping")
)
xgb_at$train(task)
#> Error: <GraphLearner:XGBoostCox> is incompatible with <CallbackTuning:mlr3tuning.early_stopping>
```

<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bblodfon** [comment]
Nice, thanks so much @be-marc, it works! 

Btw, is there a more automatic way to get the learner id? I have constructed two possible xgboost graph learners with different ids, `XGBoostCox` and `XGBoostAFT` so I am now simply checking the value of `state$model$XGBoostCox` if it is NULL or not in the above code to see which one I should use in the pipe path.

**Comment by bblodfon** [comment]
Okay, the answer was already there, since I can get the `learner = context$instance$objective$learner` and therefore I can always take the `learner$id` (of the graph learner) which it so happens in my case to be the same as the prefix in the parameters (that's how I constructed in the first place). But of course you wouldn't expect this to work in general!

**Comment by bblodfon** [comment]
Nope, I take it back! I can't get the learner id with the way above automatically! Unless there is some way to store this `learner$id` when used inside `on_optimization_begin` and used later inside `on_eval_after_benchmark` and `on_result`?

**Comment by be-marc** [comment]
I don't know if I understand your question correctly yet.  When we tune a graph learner, the id is always the id of the graph learner. The `branch.selection` parameter shows the id of the learner/ active path. You could access this parameter to get the right prefix in `on_result`.  However, you only need this step when you use an `AutoTuner` or do nested resampling. If not you can remove `on_result`. Ids can be changed like this.

```r
learners = list(
 # Change id of learner and prefix in graph learner parameter set
  kknn = lrn("classif.xgboost", id = "xgboost_1"), 
  svm = lrn("classif.xgboost", id = "xgboost_2")
)

graph = ppl("branch", lapply(learners, po))
learner = as_learner(graph)

# Change id of graph learner
learner$id = "branching"
``

**Comment by bblodfon** [comment]
Sorry, I know it is confusing! So what is hapenning here is that the `id` of the graph learner is the same as the `id` of the xgboost learner it encapsulates, i.e. see below how I create this graph learner object:
```
xgboost_cox = mlr3pipelines::ppl('distrcompositor',
              learner = lrn('surv.xgboost', nthread = nthreads,
                booster = 'gbtree', fallback = lrn('surv.kaplan'),
                objective = 'survival:cox', id = 'XGBoostCox'),
              estimator = 'kaplan',
              form = 'ph',
              overwrite = TRUE,
              graph_learner = TRUE
            )
xgboost_cox$id = 'XGBoostCox'
xgboost_cox$label = 'Extreme Gradient Boosting (Cox)'
```
I have a similar xgboost graph learner with AFT prefixes. So, I implement the callback like [this](https://github.com/bblodfon/survmob/blob/main/R/callbacks.R#L75) and it now works. But I guess the `context$instance$objective$learner$id` is the graph learner's id which just happens to be the same as the prefix of the parameters of the xgboost learner as it is created from the above code (also see `on_result` code). It was just a convenience I had adopted to make the parameter spaces as well with the `id` prefix and it just so happened to be useful in here as well :)
