### ISSUE TITLE
FitnessFunction: Think about naming

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3tuning#39]
Is it good to have the word "function" in the name of that class? This might inflict that the created object might be a function but in fact its a class. 
I see upcoming confusion.

Why not something similar to mlr like `TuneWrapper`?

**Comment by jakob-r** [comment]
The created object is not a class. That would be weird.
It might not be an object of the R-Class `function` but it is a function you can evaluate using `$eval()` so I think the name can stay.

**Comment by berndbischl** [comment]
> s it good to have the word "function" in the name of that class? This might inflict that the created object might be a function but in fact its a class.
> I see upcoming confusion.
> 
> Why not something similar to mlr like `TuneWrapper`?

i think the name is good. we ARE in this case really create a "fitness function". you can make counter offer for a better name, but TuneWrapper is wrong / much worse as a name. 

I vote for closing this and keeping the name

**Comment by pat-s** [comment]
@jakob-r 	I meant the created object is of class `FitnessFunction`

```r
class(ff)
[1] "FitnessFunction" "R6"
```

I know that the `.$eval()` function from the class executes the "function" actually in this case. But I was specifically referring to the class name.

> i think the name is good. we ARE in this case really create a "fitness function". you can make counter offer for a better name, but TuneWrapper is wrong / much worse as a name.

Hmm. I see that the main purpose is the "function" here which is in fact the `.$eval()` member function. However, as it is a "container" (the class object), it sounds weird to me if it has the word "function" in it.

This is just a subjective point of view, nothing critical of course. I just wanted to share my thoughts and hear yours :)
When I think of the class object as a "container" that stores everything (functions, getters, results) than "TuneWrapper" actually makes more sense in my mind.

"FitnessFunction" sounds catchy and easy when you say it out loud. 
Better naming suggestions are not easy.
For me possible words that would fit here in general are "container", "tune", "fitness", "optim", "box".

**Comment by berndbischl** [comment]
you really have to mention concrete alternatives regarding names so we can move forward. not just single words.

the class represents a mathematical fitness function, which is here  an R6 object, not an R function. that seems to be your problem.

FitnessEvaluator? 
FitnessLogger?
FitnessArchive?
PerformanceEvaluator?
PerformanceArchive?

Comments: I dont like "logger". PerformanceEvaluator maybe best?

**Comment by jakob-r** [comment]
- ...Objective
- ...Task
- ...Target

But I would stay with FF

**Comment by pat-s** [comment]
> the class represents a mathematical fitness function, which is here an R6 object, not an R function. that seems to be your problem.

sort of. I mean its just a name in the end and users will just live with it.
We should not spent too much time on that..

All "Fitness" mixes sound a bit like "gym/sports". 
"PerformanceEvaluator" sounds good. Since its a "container" something like "OptimizationEvaluator" makes also sense.

In the end this class is about optimizing hyperpars with given inputs (learners, tasks, paramset) so having something like "optim*" combined with "eval" makes sense to me (since the primary purpose is the evaluation of the inputs using the `.$eval()` member function).

Bernd and Jakob are both for keeping the current name so I think we go with that? :) Thanks for your sharing your thoughts on this.

**Comment by berndbischl** [comment]
> All "Fitness" mixes sound a bit like "gym/sports".

"fitness" comes from evolutionary optimization.

lets rename to PerformanceEvaluator. Or even ResampledPerfEvaluator 
I think thats best

**Comment by jakob-r** [comment]
I will rename it to PerformanceEvaluator then

**Comment by jakob-r** [comment]
done in mlr3tuning and mlr3book

**Comment by berndbischl** [comment]
quoting from testthat "you rock" ;-)

**Comment by pat-s** [comment]
Cool! I like the name a lot more than the previous one.
