### ISSUE TITLE
Replace `settings` with param set

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3tuning#4]
Tuners and Terminators should have slots `$param_set` and `$param_vals` so that we can tune them, too.

**Comment by mllg** [comment]
We can copy some code from here: https://github.com/mlr-org/mlr3/blob/master/R/Learner.R#L107

**Comment by jakob-r** [comment]
I am afraid this will create total confusion but it is logical so ??? let's do it?

**Comment by berndbischl** [comment]
Ermm I don't know? We don't really need to tune Tuners? If it is really SIMPLE to do and DOES NOT lead to confusion I would do this

**Comment by ja-thomas** [comment]
I mean what is really the use case for this? 

Probably when we would like to configure mlrMBO or other tuners, but IF(!) we would like to do this at some point, is it really necessary to bake this into mlr3? Couldn't we just write a small wrapper function and use mlrMBO or a different tuning/AC package?

**Comment by berndbischl** [comment]
we dont want this now

**Comment by berndbischl** [comment]
i guess we do want this

**Comment by berndbischl** [comment]
really on the fence here. the "meta optimization" is not really the issue. but i dislike a bit that
we now have an inconsistent system.

**Comment by mllg** [comment]
AFAIR we agreed on using a regular `ParamSet`.

**Comment by berndbischl** [comment]
> AFAIR we agreed on using a regular `ParamSet`.

yes i converged to that, too. will do that

**Comment by berndbischl** [comment]
sorry, for the back-and-forth, but i guess i dont want this (now....)
the Tuner and Terminator are currently nicely state-less and basically immutable
introducing a paramset, would change that, as "values" can be changed during the lifecycle
i would settings rather  have defined on constrcution, then they are private and cannot be mutated anymore.

does that make sense?
@mllg do you remember any big advantage that a paramset would give us?

**Comment by jakob-r** [comment]
I think we are talking about the interface of setting parameters. We want to use the same everywhere and thatswhy the use of a ParamSet. 

Just because for ParamSets there is the possibility to change values does not mean that we guarantee that it leads to feasible results. From a technical point of view nothing is immutable in R anyways.

**Comment by mllg** [comment]
Have we reached a decision yet?

**Comment by berndbischl** [comment]
use param sets for tuners and terminators, try it pls

**Comment by mllg** [comment]
Replaced with param sets.
