### ISSUE TITLE
evaluate_default breaks with graph learner

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3tuning#406]
see https://stackoverflow.com/questions/77855462/error-when-performing-hpo-with-hyperband-and-mbo-with-helper-function-auto-tuner

**Comment by sebffischer** [comment]
Hmm, now there is just a different error message that still does not make it clear that this is not a user error but a bug in mlr3?

**Comment by be-marc** [comment]
So it's not really a bug. There is no default value for nrounds in the `ParamSet` of XGBoost so `defaut_values()` can't find one either. I fixed this a few days ago in `default_values.LearnerXGBoost` but it will not work for `GraphLearner`.

**Comment by be-marc** [comment]
You will get the error message from mlr3 when you use a graph learner.

**Comment by sebffischer** [comment]
I think we should implement a `default_values.GraphLearner` method that looks something like


```r
default_values.GraphLearner = function(x) {
  vals = list()
  for (obj in x$graphs) {
      if (test_class(x, "PipeOpLearner")) {
        vals = c(vals, default_values(x$learner))
      }
    }
    return(vals
}

**Comment by be-marc** [comment]
Tried this and I think it gets really ugly with the ids. You need to match the ids in the search space. `evaluate_default = TRUE` is a callback now that simply does not work with graph learner.
