### ISSUE TITLE
Tuning: GridSearch on mixed int/numeric space

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3tuning#42]
I want to tune over the following Parameter Space:
```r
param_set = paradox::ParamSet$new(
  params = list(
    paradox::ParamDbl$new("classif.svm.cost", lower = 0.1, upper = 1),
    paradox::ParamInt$new("pca.rank.",  lower = 1, upper = 3)
  )
)
```

calling 
```r
pe = PerformanceEvaluator$new(iris, learner, resampling, param_set)
terminator = TerminatorEvaluations$new(30)
tuner = TunerGridSearch$new(pe, terminator)$tune()
```

I would now assume that it searches through `pca.rank` 1,2,3 and `cost` `0.1, 0.2, 0.3, ..., 1`,
as this would evaluate to 30 evaluations.

Instead I get `WARN  [11:38:30.936] Set number of maximal evaluations to 21 to avoid multiple computation of the same grid.`

I.e. it seems to somehow compute a weird resolution from the evaluations?

**Comment by jakob-r** [comment]
In this case we probably want to have a `TunerDesign` and the design could be generated in `paradox` using
```r
design = generate_design_grid(param_set, 10)
```

**Comment by berndbischl** [comment]
@pfistfl first of all it would have been nice to have fully reproducible example, so i can now test against it. i do think it must be possible to find a learner with an int and a num param..

**Comment by berndbischl** [comment]
this is a fully reproducible example 
```
task = mlr_tasks$get("iris")
learner = mlr_learners$get("classif.rpart")
resampling = mlr_resamplings$get("holdout")
measure = mlr_measures$mget("classif.ce")
param_set = ParamSet$new(
  params = list(
    ParamDbl$new("cp", lower = 0.1, upper = 1),
    ParamInt$new("minsplit",  lower = 1, upper = 3)
  )
)

pe = PerformanceEvaluator$new(task, learner, resampling, measure, param_set)
terminator = TerminatorEvaluations$new(30)
tuner = TunerGridSearch$new(pe, terminator)$tune()
```

it creates warning

```
WARN  [23:59:06.956] Set number of maximal evaluations to 15 to avoid multiple computation of the same grid.
INFO  [23:59:06.962] Evaluating 15 configurations
INFO  [23:59:07.053] Benchmark with 15 resampling iterations
```

**Comment by berndbischl** [comment]
this is simply a misdesign in TunerGridSearch. 

I dont think it makes any sense to couple the GridSearch with the Terminator, and then t. A GridSearch by its name(!) says that it defines the number of evals. 

I am pretty sure I complained about this multiple times.

The Terminator in the GridSearch should be NULL. and using something else should be an error.

**Comment by jakob-r** [comment]
> The Terminator in the GridSearch should be NULL. and using something else should be an error.

`terminator = TerminatorInfinite()` ?

**Comment by mllg** [comment]
A terminator with time budget does make sense iff the points in the grid are evaluated in a random order. I'd suggest to proceed as follows:

* All tuners are allowed to self-terminate (grid search, random search with given number of points, MBO with x iterations, ...).
* You *may* throw in some additional terminators, but it is your fault if this makes no sense.

**Comment by berndbischl** [comment]
I have locally begun to fix this but this is by far not the only problem in the design

**Comment by berndbischl** [comment]
And already kinda used Michels policy from above

**Comment by berndbischl** [comment]
Well not exactly

**Comment by berndbischl** [comment]
For mbo it seems a bit confusing to also allow budget and iterations constraints from mbo as they are all the same. We really need to talk. Pls don't change code now

**Comment by berndbischl** [comment]
this is fixed now
