### ISSUE TITLE
Progress bar for tuning

### ISSUE THREAD

**Issue by oren0e** [mlr-org/mlr3tuning#43]
**Edit: Redirected from mlr**

https://github.com/mlr-org/mlr/issues/2605#event-2432409016

It would be nice to have an optional progress bar that will show, either in console or in a separate window, the % done.

Thanks!

**Comment by oren0e** [comment]
By the way - currently I do not have anything that can show me what % of the task was done. It is very inconvenient because tuning parameters takes a lot of time and I want to know where do I stand. I don't know if I have days or hours left to 100%.

**Comment by mllg** [comment]
A progress bar is currently not feasible for various reasons (terminators are too flexible, `benchmark()` output would be suppressed, parallelization, ...). I've added some log output though, at least you can now estimate the remaining runtime from the output.
