### ISSUE TITLE
Feature request: `getTuneResult`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3tuning#44]
From the old mlr help page:

"Returns the optimal hyperparameters and optimization path after training."

Could inherit the options of `getTuneResultOptPath()`.

**Comment by mllg** [comment]
You can now do something like this:

```r
task = mlr3::mlr_tasks$get("iris")
learner = mlr3::mlr_learners$get("classif.rpart")
resampling = mlr3::mlr_resamplings$get("holdout")
measures = mlr3::mlr_measures$mget("classif.ce")
param_set = paradox::ParamSet$new(
  params = list(paradox::ParamDbl$new("cp", lower = 0.001, upper = 0.1)))

terminator = TerminatorEvaluations$new(5)

at = AutoTuner$new(learner,
  resampling, measures, param_set, terminator, tuner = TunerGridSearch,
  tuner_settings = list(resolution = 10L))
at$store_bmr = TRUE

rr = mlr3::resample("iris", at, "cv3")

# tune result of first learner (basically a benchmarkresult)
tune_result = rr$learners[[1]]$bmr
unnest(tune_result$aggregate(measures, params = TRUE), "params")
```

I guess such an example should go into the book?

**Comment by berndbischl** [comment]
> I guess such an example should go into the book?

yup. the last line is a TAD too complicated. but i guess its fine for now

**Comment by pat-s** [comment]
So can we add a getter that executes the last line and accepts a learner index?

**Comment by berndbischl** [comment]
> So can we add a getter that executes the last line and accepts a learner index?

not really, also we dont "work around" normal indexing as a policy.
and you need to add that piece of code to an class which lives in mlr3tuning.
so AutoLearner is ok, but not the RR.
that can work:

auto_tuner_model = rr$learners[[1]]
auto_tuner_model$tune_path

the last can be an active binding.

@mllg 
?

**Comment by mllg** [comment]
Yes, I can make this a method of the AT. Will not easily work for RR or BMR without messing up other stuff ... we would need something like decorators for that.

**Comment by pat-s** [comment]
> the last can be an active binding.

That's what I meant^^

**Comment by mllg** [comment]
Now implemented as `tune_path`.

**Comment by pat-s** [comment]
Now in the book: https://github.com/mlr-org/mlr3book/commit/f43b37c97980668560a29028d41027955613374d.
