### ISSUE TITLE
Allow for sets of hyperparameters to fail?

### ISSUE THREAD

**Issue by SteveBronder** [mlr-org/mlr3tuning#443]
When running a model sometimes I'll get errors caused by things like xgboost requesting more memory than available. Is it possible for these instances of tuning parameters to be tossed away / ignored? It would be nice so that then the tuning can still continue even if some models fail

**Comment by be-marc** [comment]
Yes https://mlr3book.mlr-org.com/chapters/chapter10/advanced_technical_aspects_of_mlr3.html#sec-error-handling
