### ISSUE TITLE
Update docs on early stopping rounds for xgboost

### ISSUE THREAD

**Issue by SteveBronder** [mlr-org/mlr3tuning#445]
Code no longer works from blog post below

https://mlr-org.com/gallery/optimization/2022-11-04-early-stopping-with-xgboost/

```R
task$set_row_roles(split$test, "test")
Error in task_set_roles(private$.row_roles, rows, roles, add_to, remove_from) : 
  Assertion on 'roles' failed: Must be a subset of {'use'}, but has additional elements {'test'}.
```

**Comment by be-marc** [comment]
Hey, sorry we changed the early stopping mechanism recently. Here is a preview of the book chapter on early stopping https://829-merge--mlr3book.netlify.app/chapters/chapter15/validation_and_internal_tuning.
