### ISSUE TITLE
unnesting of x_domain by default in as.data.table(archive) and print

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#451]
see issue mlr3misc 

https://github.com/mlr-org/mlr3misc/issues/119

i dont think that this should be done by default.

the whole point is that "x_domain" can contain pretty much anything, in terms of datatypes and it unclear how to robustly convert this into dt cols.

this is exactly why in the searchspace we only operate on scalar cols.

these things should likely be done

a) mlr3misc should better doc under which conditions it can robustly do the conversion

b) tuning should not do the convert by default

c) tuning need a test so that this does not break

**Comment by berndbischl** [comment]
the other option is, which would likey then only require one change, 
is to say this in mlr3misc:

unnest requires a list of list of "objects". if all of them are "scalars" we convert to a scalar col, otherwise to a list col. that is a more robust and useful operation.

i would STILL NOT by default unnest x_domain due to the above reasons

**Comment by be-marc** [comment]
Done #456
