### ISSUE TITLE
Compatibility with mlr3mbo and XGBoost's early stopping

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3tuning#452]
When using XGBoost with early stopping and `mlr3mbo`, I'm running into an error `Error: Learner (regr.xgboost): Configure field 'validate' to enable early stopping`. See https://github.com/mlr-org/mlr3mbo/issues/163 for a reprex.

@sebffischer has poked at it (see [thread on MM](https://lmmisld-lmu-stats-slds.srv.mwn.de/mlr/pl/xfrjye1u57fqjbbgr8ykckwmwy)), indicating that a fix would involve `mlr3tuning` as well.

**Comment by be-marc** [comment]
Sorry that you had to deal with this. Should be fixed when mlr3tuning 1.0.2, bbotk 1.1.1 and mlr3mbo 0.2.6 are on CRAN.

**Comment by be-marc** [comment]
All on CRAN now.
