### ISSUE TITLE
Syntactic sugar for simple tuning

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3tuning#46]
Maybe this is a common enough case
```r
ff <- PerformanceEvaluator$new(task, lrn, cv, ps)
tuner <- TunerRandomSearch$new(ff, TerminatorEvaluations$new(10))
result <- tuner$tune()$tune_result()
```
that it would be worth it to define a shortcut, e.g.
```r
result <- TuneRandom(task, lrn, cv, ps, 10)
```

**Comment by berndbischl** [comment]
@mllg said in #9 
So you want a tune(task, learner, resampling, measures, param_set, tuner, ctrl) function?

**Comment by berndbischl** [comment]
we do this in mlr3sugar now
