### ISSUE TITLE
Proper implementation of early_stopping_rounds for xgboost

### ISSUE THREAD

**Issue by chuckgrigsby0** [mlr-org/mlr3tuning#463]
I am trying to implement early stopping using the xgboost algorithm. However, I receive an error when I use callbacks = clbk("mlr3tuning.early_stopping"). 

Error: Element with key 'mlr3tuning.early_stopping' not found in DictionaryCallbacks!

There also seems to be an issue with the `early_stopping_set` parameter. I have tried following these examples: 

https://mlr3tuning.mlr-org.com/reference/mlr3tuning.early_stopping.html. 
https://mlr-org.com/gallery/optimization/2022-11-04-early-stopping-with-xgboost/

Is there an alternative solution to make early stopping work? 

Thanks for anyone's help!

Regards,
Chuck

**Comment by be-marc** [comment]
Sorry the API changed recently. See the new book chapter on internal tuning for examples https://829-merge--mlr3book.netlify.app/chapters/chapter15/predsets_valid_inttune.

**Comment by be-marc** [comment]
You're welcome. The chapter is now merged to the book -> https://mlr3book.mlr-org.com/chapters/chapter15/predsets_valid_inttune.html
