### ISSUE TITLE
Autotuner: If the learner has configured param_vals, AutoTuner looses them

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3tuning#51]
The following does not error, but does not behave as it should: 

```r
library(mlr3)
library(mlr3tuning)
library(paradox)

# Define the ParamSet
ps = ParamSet$new(params = list(ParamDbl$new(id = "cp", lower = 0, upper = .8)))
lrn = mlr_learners$get("classif.rpart", param_vals = list(minsplit = 2))
terminator = TerminatorEvaluations$new(20)
```

=>  We set an additional hardcoded minsplit

```r
at = AutoTuner$new(lrn, "cv3", measures = "classif.acc", ps,
  terminator, tuner = TunerRandomSearch, tuner_settings = list())
```
> at$param_set$values
named list()
=> We seem to loose the param_vals here

```r
at$train("iris")
```

> > at$param_set$values
$cp
[1] 0.3260657

**Comment by berndbischl** [comment]
really check the assigment of the values in the AutoTuner, i am working on this also in a branch where a tuner assigns values to a instance

a line like this is dangerous

      learner$param_set$values = instance$selected_config


--->

we really need unit tests for this issue

**Comment by berndbischl** [comment]
it seems that this is already fixed now and @mb706 even added a test here

https://github.com/mlr-org/mlr3tuning/commit/16927701a5a840d069756514077c1d805142c74c
