### ISSUE TITLE
multiple measures?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#53]
a) simply for logging
b) so we support multicrit optimization

note that this needs to be properly doced in the interface

**Comment by berndbischl** [comment]
we also need to check the mlr3sugar interface so a vector of measures is allowed there

**Comment by mllg** [comment]
It is already possible to provide multiple measures.

**Comment by berndbischl** [comment]
i know. but this needs to be better tested.
also, i dont want to IMPLEMENT this now, but we need to be sure that we can multcrit tuning later, too. 
i at least want to "devel doc" this a bit for now

**Comment by berndbischl** [comment]
i tested this a bit, seems fine for now

**Comment by berndbischl** [comment]
i updated the docs a bit on this point. we can close here
