### ISSUE TITLE
carefully read and check autotuner

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#62]

**Comment by berndbischl** [comment]
the whole ting is pretty weird:
- it is very unclear how the member of the superclass are set in initialize, whether we map them to the members of the passed learner
- what is actually stored in "state" now for the AT?
- i called the passed param_set now "tune_ps" maybe not the best name

**Comment by berndbischl** [comment]
i also disabled a block of code in the unit test

**Comment by berndbischl** [comment]
the example also seems to be imperfect and somewhat unfinished

**Comment by mllg** [comment]
NB: `tune_path` does not exists as documented.

**Comment by berndbischl** [comment]
in general seems fine now, we should open specific issues
