### ISSUE TITLE
impleme irace tuning

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#63]

**Comment by mllg** [comment]
Extra package? Or just postponed?

**Comment by berndbischl** [comment]
might be less necessary if we have HB
also: i dont like these issues ala "do this big thing, which might be useful"

i guess i reopen this

**Comment by jakob-r** [comment]
Thanks for the offer but @be-marc already finished this task.
Are you aware of mlr3hyperband? Theoretically it should not be any problem to run similar experiments.

If you talk about reproducing the experiments exactly: I guess the devil is in the detail. 

@be-marc Do you have any feedback what could be improved in Irace?

**Comment by mllg** [comment]
> I would also be very interested in any comparisons with hyperband, since they are conceptually very similar. How easy would be to reproduce the experiments of the hyperband paper using mlr3 ?

Yes, it should be really easy. If you want to cooperate on a benchmark study, please drop us a mail or join our mattermost group chat (https://lmmisld-lmu-stats-slds.srv.mwn.de/mlr_invite/).

**Comment by berndbischl** [comment]
@MLopez-Ibanez wrt further studies: just email me, always happy to discuss this - with you

**Comment by MLopez-Ibanez** [comment]
> @MLopez-Ibanez wrt further studies: just email me, always happy to discuss this - with you

Done.
