### ISSUE TITLE
how can we add futher interesting extracted info to the benchmark result during tuning?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#70]
this need to be checked and doced

**Comment by berndbischl** [comment]
@mllg said we can simply add cols to the dt.
more interesting question is WHERE do we add something?
does mlr3tuning add something? do we enable the user to do this? thru hooks?

**Comment by mllg** [comment]
This is not important now. We can do everything w/o adding additional columns. For the sake of simplicity, lets just remove the hooks for now.

**Comment by berndbischl** [comment]
sure, this is a bonus issue for later and the hooks i already marked for removal

**Comment by berndbischl** [comment]
it already became relevant for hyperband. and is nontrivial. 
the problem is:
the internal state is the BMR, but we actually would like to add info on the "archive level" in most cases

**Comment by berndbischl** [comment]
also if i add to the BMR, now aggregate seems to drop these columns? which makes it impossible to do anything?

**Comment by berndbischl** [comment]
in hyperband we currenty generate a second table including hashes, so one can join later. not really perfect

**Comment by berndbischl** [comment]
michels adds an info table to the BMR in mlr3

**Comment by mllg** [comment]
The table is in mlr3 as `bmr$rr_data`.
