### ISSUE TITLE
maybe we need a TerminatorNone 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#75]
or under a better name.

for grid search. unclear.

or we set evals exactly to gridsize?
or each optim algorithm has its own additional termination it can trigger?

**Comment by mllg** [comment]
> or each optim algorithm has its own additional termination it can trigger?

This.

**Comment by berndbischl** [comment]
we should care document and think about that a tuner can "stop itself"
thats at least a bit suboptimal if a complex stop criterion can internally be triggered. 
we rather want unified control over this from mlr?

**Comment by mllg** [comment]
If in doubt, set the termination very generously. E.g., do run MBO with 1e7 iterations, and have it stopped with one of our Terminators. I don't see a problem here.

It's more the other way around: If you have a tuner which behaves differently depending on the remaining budget, you need to be able to set a reasonable budget.

**Comment by berndbischl** [comment]
i added the TerminatorNone and documented the concept better in ?Terminator
