### ISSUE TITLE
Terminator:remaining

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#79]
Again, it is NOT documented in the abstract base class what the general format and meaning of this is. It is also very clear that some Termointors will not be able to support this,
e.g. a Stagnation concept does not know "how much is left"

I am on the edge here, maybe this should stay. Also checked how this is logged in eval_batch, we always add an extra line in the logging this seems a bit verbose

**Comment by berndbischl** [comment]
more: TerminatorEvluations does not need a state, i removed that. now should i only introduce this so we have this logging info?

**Comment by berndbischl** [comment]
remaining should probably return a list of
* total
* value
* units (string)

**Comment by mllg** [comment]
Lets just simplify this here. A Terminator can return the number of remaining iterations (so that we can adept the batch size accordingly), or NA if this is not applicable. Everything else is just used for output.

**Comment by berndbischl** [comment]
> A Terminator can return the number of remaining iterations (s

thats only applicable to exactly one Terminator. I would then vote to remove the whole concept.

**Comment by berndbischl** [comment]
> so that we can adept the batch size accordingly

an exactly this i also would not do now, but simply document what happens, i.e. that we can slightly over-allocate the budget if the user selects param suboptimally

**Comment by berndbischl** [comment]
i have removed this now, it only slows us down and is really not this useful / central now for tuning.
if we change our opinion:
https://github.com/mlr-org/mlr3tuning/commit/843d93212299e29ec475aec05c8a03f1b60c4bb4
