### ISSUE TITLE
should tuners and termintors go into a dict?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#83]
yes, because of consitency? @mllg

**Comment by mllg** [comment]
Yes.

**Comment by berndbischl** [comment]
@mllg how is supposed to work when the objects need non trivial other objects to be constructed? for the Tuner I need the PerfEval object?

I guess I have then to pass this to mlr_tuner$get? 
but how to I list properies of the tuner in the as.data.table of the dict if i cannot construct the object?
and the properties are not static of the class....?

**Comment by berndbischl** [comment]
https://github.com/mlr-org/mlr3tuning/tree/dicts

**Comment by berndbischl** [comment]
also: do we allow casting from strings for them in asserts? answer probably no, because the cannot be constructed arg-lessly?

**Comment by mllg** [comment]
@mb706 had the same issues with some pipeops, probably ask him how he solved it.

**Comment by mb706** [comment]
In mlr3pipelines I add each class to `mlr_pipeops` using `mlr_pipeops$add()`, but one of the arguments of `add()` is an example object to be given to the constructor. This is a simple dummy object that leads to "typical" behaviour. See e.g. [PipeOpLearner](https://github.com/mlr-org/mlr3pipelines/blob/3b083301af8c73d3484575806f49177b5839584e/R/PipeOpLearner.R#L68). This example object is then used in `as.data.table`.

The behaviour to be listed in `as.data.table` could in theory depend substantially on the object used for construction, but I have not had this problem yet in mlr3pipelines. If it comes up, I believe I would probably give multiple different example objects to the Dictionary, let `as.data.table()` construct the class with each object in turn, and check what properties stay the same and what properties change. The changing properties could then be listed as `NA`.

**Comment by berndbischl** [comment]
tuners can now be constructed without constructor args, so this is not a problem anymore. 
we still should list new properties "param_classes" in dictionory

https://github.com/mlr-org/mlr3tuning/tree/dicts
--

**Comment by mllg** [comment]
Now in dicts.
