### ISSUE TITLE
RS: maybe default setting for the batchsize should be from terminator?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#89]

**Comment by berndbischl** [comment]
also what out that i set the current default batch_size to one t oavoid stupid problem. 
this makes behvior more robust but will result in 0 parellization

**Comment by berndbischl** [comment]
also note that the batchsize for GS is currently 10, they should be similar?

**Comment by mllg** [comment]
`batch_size` is 1 which seems to be a good default.
